from django.db import models
from django.forms import ModelForm


AREA = (
        ("Rogers Park", "Rogers Park"),
        ("West Ridge", "West Ridge"),
        ("Uptown", "Uptown"),
        ("Lincoln Square", "Lincoln Square"),
        ("North Center","North Center"),
        ("Lake View","Lake View"),
        ("Lincoln Park", "Lincoln Park"),
        ("Near North Side","Near North Side"),
        ("Edison Park", "Edison Park"),
        ("Norwood Park", "Norwood Park"),
        ("Jefferson Park", "Jefferson Park"),
        ("Forest Glen", "Forest Glen"),
        ("North Park", "North Park"),
        ("Albany Park","Albany Park"),
        ("Portage Park", "Portage Park"),
        ("Irving Park", "Irving Park"),
        ("Dunning", "Dunning"),
        ("Montclaire", "Montclaire"),
        ("Belmont Cragin", "Belmont Cragin"),
        ("Hermosa","Hermosa"),
        ("Avondale","Avondale"),
        ("Logan Square", "Logan Square"),
        ("Humboldt Park", "Humboldt Park"),
        ("West Town", "West Town"),
        ("Austin", "Austin"),
        ("West Garfield Park", "West Garfield Park"),
        ("East Garfield Park", "East Garfield Park"),
        ("Near West Side","Near West Side"),
        ("North Lawndale", "North Lawndale"),
        ("South Lawndale", "South Lawndale"),
        ("Lower West Side", "Lower West Side"),
        ("Loop","Loop"),
        ("Near South Side","Near South Side"),
        ("Armour Square", "Armour Square"),
        ("Douglas","Douglas"),
        ("Oakland", "Oakland"),
        ("Fuller Park", "Fuller Park"),
        ("Grand Boulevard", "Grand Boulevard"),
        ("Kenwood","Kenwood"),
        ("Washington Park", "Washington Park"),
        ("Hyde Park","Hyde Park"),
        ("Woodlawn","Woodlawn"),
        ("South Shore", "South Shore"),
        ("Chatham", "Chatham"),
        ("Avalon Park", "Avalon Park"),
        ("South Chicago", "South Chicago"),
        ("Burnside", "Burnside"),
        ("Calumet Heights", "Calumet Heights"),
        ("Roseland", "Roseland"),
        ("Pullman", "Pullman"),
        ("South Deering", "South Deering"),
        ("East Side","East Side"),
        ("West Pullman", "West Pullman"),
        ("Riverdale", "Riverdale"),
        ("Hegewisch", "Hegewisch"),
        ("Garfield Ridge", "Garfield Ridge"),
        ("Archer Heights", "Archer Heights"),
        ("Brighton Park", "Brighton Park"),
        ("McKinley Park", "McKinley Park"),
        ("Bridgeport","Bridgeport"),
        ("New City", "New City"),
        ("West Elsdon", "West Elsdon"),
        ("Gage Park","Gage Park"),
        ("Clearing","Clearing"),
        ("West Lawn","West Lawn"),
        ("Chicago Lawn", "Chicago Lawn"),
        ("West Englewood", "West Englewood"),
        ("Englewood", "Englewood"),
        ("Greater Grand Crossing","Greater Grand Crossing"),
        ("Ashburn", "Ashburn"),
        ("Auburn Gresham", "Auburn Gresham"),
        ("Beverly","Beverly"),
        ("Washington Heights","Washington Heights"),
        ("Mount Greenwood","Mount Greenwood"),
        ("Morgan Park","Morgan Park"),
        ("O'Hare", "O'Hare"),
        ("Edgewater","Edgewater"))

AREA_DICT = dict(AREA)

class Input(models.Model):

    area = models.CharField(max_length=50, choices=AREA)
